name: Publish Docker Image

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Set image name and tag
        id: meta
        run: |
          OWNER=$(echo "${GITHUB_REPOSITORY%%/*}" | tr '[:upper:]' '[:lower:]')
          REPO=$(echo "${GITHUB_REPOSITORY##*/}" | tr '[:upper:]' '[:lower:]')
          
          # Determine if this is a tag push
          if [ -n "${GITHUB_REF##refs/tags/}" ] && [ "${GITHUB_REF}" != "${GITHUB_REF##refs/tags/}" ]; then
            # It's a tag push
            VERSION_TAG="${GITHUB_REF#refs/tags/}"
            IMAGE_TAG="ghcr.io/$OWNER/$REPO:$VERSION_TAG"
          else
            # It's a branch push (like main)
            IMAGE_TAG="ghcr.io/$OWNER/$REPO:prerelease-latest"
          fi

          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Build Docker image
        run: docker build . --file Dockerfile --tag $IMAGE_TAG

      - name: Push Docker image
        run: docker push $IMAGE_TAG
