name: Publish Docker Image

permissions:
  contents: read
  packages: write

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'  # adjust if your tags have different format


jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Set image name and tag
        id: meta
        run: |
          OWNER=$(echo "${GITHUB_REPOSITORY%%/*}" | tr '[:upper:]' '[:lower:]')
          REPO=$(echo "${GITHUB_REPOSITORY##*/}" | tr '[:upper:]' '[:lower:]')

          if [[ "$GITHUB_REF" == refs/tags/* ]]; then
            VERSION_TAG="${GITHUB_REF#refs/tags/}"
            IMAGE_TAG="ghcr.io/$OWNER/$REPO:$VERSION_TAG"
            LATEST_TAG="ghcr.io/$OWNER/$REPO:latest"
          else
            RANDOM_ID=$(head /dev/urandom | tr -dc a-z0-9 | head -c 8)
            IMAGE_TAG="ghcr.io/$OWNER/$REPO:beta-$RANDOM_ID"
            LATEST_TAG="ghcr.io/$OWNER/$REPO:beta"
          fi

          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV

      - name: Build Docker image
        run: docker build . --file Dockerfile --tag $IMAGE_TAG

      - name: Push Docker image
        run: docker push $IMAGE_TAG

      - name: Push latest tag if release
        if: ${{ env.LATEST_TAG != '' }}
        run: |
          docker tag $IMAGE_TAG $LATEST_TAG
          docker push $LATEST_TAG
